### PR TITLE
feat(*): second rewrite

### PR DESCRIPTION
**Pull request by J-Human**
**Please describe what the pull request is about, and what this aims to do:**
This is a fixed version of #2.

This PR rewrites most files, as well as additions of meta files, and general cleanup. It is currently a WIP. It aims to make this repository look better.

Currently these are being implemented:
 - [x] .gitattributes
 - [x] Issue and PR templates.
 - [x] General ReadMe file makeover.
 - [x] LICENSE.
 - [x] CODEOWNERS.
 - [x] CODE_OF_CONDUCT.
 - [x] Repository settings.
 - [x] Workflows (if needed).
 - [x] More changes.

**Details on why this pull request should be merged:**
I plan to make the bio better.

**Any alternative pull requests or issues that work on this:**
None.

**Additional details:**
N/A.

### CODE REVIEW

**Review by RollingDeveloper — APPROVED** [review]

**Comment by J-Human** [comment]
Setting this PR branch as the GH-pages base since it's more updated. Once this is merge, I'll switch that. 👍🏼

**Comment by J-Human** [comment]
Seems like everything has been done, let's merge this. 🎉

**Comment by J-Human** [comment]
Alright, gonna merge this since all needed refactors is complete. 🎉

**Pull request merged**
